/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        lumina: {
          dark: '#0A0A0C',
          darkSurface: '#121216',
          darkBorder: '#1A1A20',
          darkElevated: '#1E1E2A',
          light: '#F8F9FA',
          lightSurface: '#FFFFFF',
          lightBorder: '#F3F4F6',
          primary: '#2563EB',
          primaryHover: '#1D4ED8',
          secondary: '#8B5CF6',
          cyan: '#06B6D4',
        },
        "inverse-primary": "#524ad1",
        "on-primary-fixed": "#110069",
        "on-secondary-fixed-variant": "#454747",
        "primary-fixed": "#e3dfff",
        "surface-bright": "#3a3939",
        "surface": "#131313",
        "on-error-container": "#ffdad6",
        "background": "#131313",
        "on-tertiary-fixed-variant": "#763300",
        "on-secondary": "#2f3131",
        "surface-tint": "#c4c0ff",
        "on-tertiary-container": "#ffc8ab",
        "surface-container-highest": "#353534",
        "indigo-glow": "rgba(79, 70, 206, 0.3)",
        "secondary-fixed": "#e2e2e2",
        "on-surface-variant": "#c8c4d6",
        "secondary": "#c6c6c7",
        "secondary-fixed-dim": "#c6c6c7",
        "error-container": "#93000a",
        "outline": "#918fa0",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#392db9",
        "primary-container": "#4f46ce",
        "secondary-container": "#454747",
        "on-secondary-container": "#b4b5b5",
        "on-background": "#e5e2e1",
        "obsidian-deep": "#0A0A0A",
        "primary": "#c4c0ff",
        "outline-variant": "#464554",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "tertiary": "#ffb68e",
        "surface-container-lowest": "#0e0e0e",
        "inverse-on-surface": "#313030",
        "surface-container": "#201f1f",
        "tertiary-fixed": "#ffdbc9",
        "on-primary-container": "#d2cfff",
        "inverse-surface": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "primary-fixed-dim": "#c4c0ff",
        "surface-dim": "#131313",
        "glass-stroke": "rgba(255, 255, 255, 0.12)",
        "on-tertiary-fixed": "#331200",
        "surface-variant": "#353534",
        "tertiary-fixed-dim": "#ffb68e",
        "on-surface": "#e5e2e1",
        "on-tertiary": "#532200",
        "tertiary-container": "#964300",
        "on-primary": "#2000a4"
      },
      fontFamily: {
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Be Vietnam Pro", "sans-serif"],
        "display-kpi": ["Sora", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label-caps": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "display-lg": ["Be Vietnam Pro", "sans-serif"],
        "display-lg-mobile": ["Be Vietnam Pro", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "display-lg-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }]
      },
      spacing: {
        "lg": "24px",
        "md": "16px",
        "xl": "32px",
        "container-margin": "20px",
        "xs": "4px",
        "gutter": "24px",
        "base": "4px",
        "2xl": "48px",
        "3xl": "64px",
        "sm": "8px",
        "section-gap": "120px",
        "container-max": "1280px",
        "unit": "8px",
        "margin-desktop": "64px",
        "margin-mobile": "20px"
      }
    },
  },
  plugins: [],
}
